const POKEMON_PART_1 = {
  'Bulbasaur': { hp: 45, atk: 49, def: 49, sp_atk: 65, sp_def: 65, speed: 45, type: ['Planta', 'Veneno'], moves: ['Tackle', 'Vine Whip'], spawnTier: 1 },
  'Ivysaur': { hp: 60, atk: 62, def: 63, sp_atk: 80, sp_def: 80, speed: 60, type: ['Planta', 'Veneno'], moves: ['Vine Whip', 'Razor Leaf'], spawnTier: 2 },
  'Venusaur': { hp: 80, atk: 82, def: 83, sp_atk: 100, sp_def: 100, speed: 80, type: ['Planta', 'Veneno'], moves: ['Razor Leaf', 'Solar Beam'], spawnTier: 3 },
  'Charmander': { hp: 39, atk: 52, def: 43, sp_atk: 60, sp_def: 50, speed: 65, type: ['Fuego'], moves: ['Scratch', 'Ember'], spawnTier: 1 },
  'Charmeleon': { hp: 58, atk: 64, def: 58, sp_atk: 80, sp_def: 65, speed: 80, type: ['Fuego'], moves: ['Scratch', 'Flamethrower'], spawnTier: 2 },
  'Charizard': { hp: 78, atk: 84, def: 78, sp_atk: 109, sp_def: 85, speed: 100, type: ['Fuego', 'Volador'], moves: ['Flamethrower', 'Wing Attack'], spawnTier: 3 },
  'Squirtle': { hp: 44, atk: 48, def: 65, sp_atk: 50, sp_def: 64, speed: 43, type: ['Agua'], moves: ['Tackle', 'Water Gun'], spawnTier: 1 },
  'Wartortle': { hp: 59, atk: 63, def: 80, sp_atk: 65, sp_def: 80, speed: 58, type: ['Agua'], moves: ['Water Gun', 'Bite'], spawnTier: 2 },
  'Blastoise': { hp: 79, atk: 83, def: 100, sp_atk: 85, sp_def: 105, speed: 78, type: ['Agua'], moves: ['Surf', 'Hydro Pump'], spawnTier: 3 },
  'Caterpie': { hp: 45, atk: 30, def: 35, sp_atk: 20, sp_def: 20, speed: 45, type: ['Bicho'], moves: ['Tackle'], spawnTier: 1 },
  'Metapod': { hp: 50, atk: 20, def: 55, sp_atk: 25, sp_def: 25, speed: 30, type: ['Bicho'], moves: ['Harden'], spawnTier: 2 },
  'Butterfree': { hp: 60, atk: 45, def: 50, sp_atk: 90, sp_def: 80, speed: 70, type: ['Bicho', 'Volador'], moves: ['Confusion', 'Gust'], spawnTier: 3 },
  'Weedle': { hp: 40, atk: 35, def: 30, sp_atk: 20, sp_def: 20, speed: 50, type: ['Bicho', 'Veneno'], moves: ['Poison Sting'], spawnTier: 1 },
  'Kakuna': { hp: 45, atk: 25, def: 50, sp_atk: 25, sp_def: 25, speed: 35, type: ['Bicho', 'Veneno'], moves: ['Harden'], spawnTier: 2 },
  'Beedrill': { hp: 65, atk: 80, def: 40, sp_atk: 45, sp_def: 80, speed: 75, type: ['Bicho', 'Veneno'], moves: ['Twineedle', 'Pin Missile'], spawnTier: 3 },
  'Pidgey': { hp: 40, atk: 45, def: 40, sp_atk: 35, sp_def: 35, speed: 56, type: ['Normal', 'Volador'], moves: ['Tackle', 'Gust'], spawnTier: 1 },
  'Pidgeotto': { hp: 63, atk: 60, def: 55, sp_atk: 50, sp_def: 50, speed: 71, type: ['Normal', 'Volador'], moves: ['Quick Attack', 'Wing Attack'], spawnTier: 2 },
  'Pidgeot': { hp: 83, atk: 80, def: 75, sp_atk: 70, sp_def: 70, speed: 101, type: ['Normal', 'Volador'], moves: ['Wing Attack', 'Fly'], spawnTier: 3 },
  'Rattata': { hp: 30, atk: 56, def: 35, sp_atk: 25, sp_def: 35, speed: 72, type: ['Normal'], moves: ['Tackle', 'Quick Attack'], spawnTier: 1 },
  'Raticate': { hp: 55, atk: 81, def: 60, sp_atk: 50, sp_def: 70, speed: 97, type: ['Normal'], moves: ['Hyper Fang', 'Quick Attack'], spawnTier: 2 },
  'Spearow': { hp: 40, atk: 60, def: 30, sp_atk: 31, sp_def: 31, speed: 70, type: ['Normal', 'Volador'], moves: ['Peck', 'Drill Peck'], spawnTier: 1 },
  'Fearow': { hp: 65, atk: 90, def: 65, sp_atk: 61, sp_def: 61, speed: 100, type: ['Normal', 'Volador'], moves: ['Drill Peck', 'Fly'], spawnTier: 2 },
  'Ekans': { hp: 35, atk: 60, def: 44, sp_atk: 40, sp_def: 54, speed: 55, type: ['Veneno'], moves: ['Poison Sting', 'Bite'], spawnTier: 1 },
  'Arbok': { hp: 60, atk: 85, def: 69, sp_atk: 65, sp_def: 79, speed: 80, type: ['Veneno'], moves: ['Bite', 'Acid'], spawnTier: 2 },
  'Pikachu': { hp: 35, atk: 55, def: 40, sp_atk: 50, sp_def: 50, speed: 90, type: ['Eléctrico'], moves: ['Thunder Shock', 'Quick Attack'], spawnTier: 1 },
  'Raichu': { hp: 60, atk: 90, def: 55, sp_atk: 90, sp_def: 80, speed: 110, type: ['Eléctrico'], moves: ['Thunderbolt', 'Thunder'], spawnTier: 3 },
  'Sandshrew': { hp: 50, atk: 75, def: 85, sp_atk: 20, sp_def: 30, speed: 40, type: ['Tierra'], moves: ['Scratch', 'Sand Attack'], spawnTier: 1 },
  'Sandslash': { hp: 75, atk: 100, def: 110, sp_atk: 45, sp_def: 55, speed: 65, type: ['Tierra'], moves: ['Slash', 'Earthquake'], spawnTier: 2 },
  'Nidoran F': { hp: 55, atk: 47, def: 52, sp_atk: 40, sp_def: 40, speed: 41, type: ['Veneno'], moves: ['Scratch', 'Poison Sting'], spawnTier: 1 },
  'Nidorina': { hp: 70, atk: 62, def: 67, sp_atk: 55, sp_def: 55, speed: 56, type: ['Veneno'], moves: ['Bite', 'Double Kick'], spawnTier: 2 },
  'Nidoqueen': { hp: 90, atk: 92, def: 87, sp_atk: 75, sp_def: 85, speed: 76, type: ['Veneno', 'Tierra'], moves: ['Body Slam', 'Earthquake'], spawnTier: 3 },
  'Nidoran M': { hp: 46, atk: 57, def: 40, sp_atk: 40, sp_def: 40, speed: 50, type: ['Veneno'], moves: ['Peck', 'Poison Sting'], spawnTier: 1 },
  'Nidorino': { hp: 61, atk: 72, def: 57, sp_atk: 55, sp_def: 55, speed: 65, type: ['Veneno'], moves: ['Horn Attack', 'Double Kick'], spawnTier: 2 },
  'Nidoking': { hp: 81, atk: 102, def: 77, sp_atk: 85, sp_def: 75, speed: 85, type: ['Veneno', 'Tierra'], moves: ['Thrash', 'Earthquake'], spawnTier: 3 },
  'Clefairy': { hp: 70, atk: 45, def: 48, sp_atk: 60, sp_def: 65, speed: 35, type: ['Normal'], moves: ['Pound', 'Sing'], spawnTier: 2 },
  'Clefable': { hp: 95, atk: 70, def: 73, sp_atk: 95, sp_def: 90, speed: 60, type: ['Normal'], moves: ['Metronome', 'Moonlight'], spawnTier: 3 },
  'Vulpix': { hp: 38, atk: 41, def: 40, sp_atk: 50, sp_def: 65, speed: 65, type: ['Fuego'], moves: ['Ember', 'Quick Attack'], spawnTier: 2 },
  'Ninetales': { hp: 73, atk: 76, def: 75, sp_atk: 81, sp_def: 100, speed: 100, type: ['Fuego'], moves: ['Flamethrower', 'Confuse Ray'], spawnTier: 3 },
  'Jigglypuff': { hp: 115, atk: 45, def: 20, sp_atk: 45, sp_def: 25, speed: 20, type: ['Normal'], moves: ['Pound', 'Sing'], spawnTier: 2 },
  'Wigglytuff': { hp: 140, atk: 70, def: 45, sp_atk: 85, sp_def: 50, speed: 45, type: ['Normal'], moves: ['Double-Edge', 'Sing'], spawnTier: 3 },
  'Zubat': { hp: 40, atk: 45, def: 35, sp_atk: 30, sp_def: 40, speed: 55, type: ['Veneno', 'Volador'], moves: ['Leech Life', 'Supersonic'], spawnTier: 1 },
  'Golbat': { hp: 75, atk: 80, def: 70, sp_atk: 65, sp_def: 75, speed: 90, type: ['Veneno', 'Volador'], moves: ['Wing Attack', 'Bite'], spawnTier: 2 },
  'Oddish': { hp: 45, atk: 50, def: 55, sp_atk: 75, sp_def: 65, speed: 30, type: ['Planta', 'Veneno'], moves: ['Absorb', 'Acid'], spawnTier: 1 },
  'Gloom': { hp: 60, atk: 65, def: 70, sp_atk: 85, sp_def: 75, speed: 40, type: ['Planta', 'Veneno'], moves: ['Acid', 'Petal Dance'], spawnTier: 2 },
  'Vileplume': { hp: 75, atk: 80, def: 85, sp_atk: 110, sp_def: 90, speed: 50, type: ['Planta', 'Veneno'], moves: ['Petal Dance', 'Solar Beam'], spawnTier: 3 },
  'Paras': { hp: 35, atk: 70, def: 55, sp_atk: 45, sp_def: 55, speed: 25, type: ['Bicho', 'Planta'], moves: ['Scratch', 'Stun Spore'], spawnTier: 1 },
  'Parasect': { hp: 60, atk: 95, def: 80, sp_atk: 60, sp_def: 80, speed: 30, type: ['Bicho', 'Planta'], moves: ['Slash', 'Spore'], spawnTier: 2 },
  'Venonat': { hp: 60, atk: 55, def: 50, sp_atk: 40, sp_def: 55, speed: 45, type: ['Bicho', 'Veneno'], moves: ['Tackle', 'Confusion'], spawnTier: 1 },
  'Venomoth': { hp: 70, atk: 65, def: 60, sp_atk: 90, sp_def: 75, speed: 90, type: ['Bicho', 'Veneno'], moves: ['Psybeam', 'Gust'], spawnTier: 2 },
  'Diglett': { hp: 10, atk: 55, def: 25, sp_atk: 35, sp_def: 45, speed: 95, type: ['Tierra'], moves: ['Scratch', 'Dig'], spawnTier: 1 },
  'Dugtrio': { hp: 35, atk: 80, def: 50, sp_atk: 50, sp_def: 70, speed: 120, type: ['Tierra'], moves: ['Dig', 'Earthquake'], spawnTier: 2 },
  'Meowth': { hp: 40, atk: 45, def: 35, sp_atk: 40, sp_def: 40, speed: 90, type: ['Normal'], moves: ['Scratch', 'Bite'], spawnTier: 1 },
  'Persian': { hp: 65, atk: 70, def: 60, sp_atk: 65, sp_def: 65, speed: 115, type: ['Normal'], moves: ['Slash', 'Bite'], spawnTier: 2 },
  'Psyduck': { hp: 50, atk: 52, def: 48, sp_atk: 65, sp_def: 50, speed: 55, type: ['Agua'], moves: ['Scratch', 'Confusion'], spawnTier: 1 },
  'Golduck': { hp: 80, atk: 82, def: 78, sp_atk: 95, sp_def: 80, speed: 85, type: ['Agua'], moves: ['Surf', 'Psychic'], spawnTier: 2 },
  'Mankey': { hp: 40, atk: 80, def: 35, sp_atk: 35, sp_def: 45, speed: 70, type: ['Lucha'], moves: ['Scratch', 'Karate Chop'], spawnTier: 1 },
  'Primeape': { hp: 65, atk: 105, def: 60, sp_atk: 60, sp_def: 70, speed: 95, type: ['Lucha'], moves: ['Cross Chop', 'Thrash'], spawnTier: 2 },
  'Growlithe': { hp: 55, atk: 70, def: 45, sp_atk: 70, sp_def: 50, speed: 60, type: ['Fuego'], moves: ['Bite', 'Ember'], spawnTier: 2 },
  'Arcanine': { hp: 90, atk: 110, def: 80, sp_atk: 100, sp_def: 80, speed: 95, type: ['Fuego'], moves: ['Flamethrower', 'Extreme Speed'], spawnTier: 3 },
  'Poliwag': { hp: 40, atk: 50, def: 40, sp_atk: 40, sp_def: 40, speed: 90, type: ['Agua'], moves: ['Water Gun', 'Hypnosis'], spawnTier: 1 },
  'Poliwhirl': { hp: 65, atk: 65, def: 65, sp_atk: 50, sp_def: 50, speed: 90, type: ['Agua'], moves: ['Bubble Beam', 'Body Slam'], spawnTier: 2 },
  'Poliwrath': { hp: 90, atk: 85, def: 95, sp_atk: 70, sp_def: 90, speed: 70, type: ['Agua', 'Lucha'], moves: ['Hydro Pump', 'Dynamic Punch'], spawnTier: 3 },
  'Abra': { hp: 25, atk: 20, def: 15, sp_atk: 105, sp_def: 55, speed: 90, type: ['Psíquico'], moves: ['Teleport'], spawnTier: 1 },
  'Kadabra': { hp: 40, atk: 35, def: 30, sp_atk: 120, sp_def: 70, speed: 105, type: ['Psíquico'], moves: ['Psychic', 'Confusion'], spawnTier: 2 },
  'Alakazam': { hp: 55, atk: 50, def: 45, sp_atk: 135, sp_def: 95, speed: 120, type: ['Psíquico'], moves: ['Psychic', 'Recover'], spawnTier: 3 },
  'Machop': { hp: 70, atk: 80, def: 50, sp_atk: 35, sp_def: 35, speed: 35, type: ['Lucha'], moves: ['Karate Chop', 'Low Kick'], spawnTier: 1 },
  'Machoke': { hp: 80, atk: 100, def: 70, sp_atk: 50, sp_def: 60, speed: 45, type: ['Lucha'], moves: ['Seismic Toss', 'Cross Chop'], spawnTier: 2 },
  'Machamp': { hp: 90, atk: 130, def: 80, sp_atk: 65, sp_def: 85, speed: 55, type: ['Lucha'], moves: ['Cross Chop', 'Earthquake'], spawnTier: 3 },
  'Bellsprout': { hp: 50, atk: 75, def: 35, sp_atk: 70, sp_def: 30, speed: 40, type: ['Planta', 'Veneno'], moves: ['Vine Whip'], spawnTier: 1 },
  'Weepinbell': { hp: 65, atk: 90, def: 50, sp_atk: 85, sp_def: 45, speed: 55, type: ['Planta', 'Veneno'], moves: ['Razor Leaf', 'Acid'], spawnTier: 2 },
  'Victreebel': { hp: 80, atk: 105, def: 65, sp_atk: 100, sp_def: 70, speed: 70, type: ['Planta', 'Veneno'], moves: ['Razor Leaf', 'Sludge Bomb'], spawnTier: 3 },
  'Tentacool': { hp: 40, atk: 40, def: 35, sp_atk: 50, sp_def: 100, speed: 70, type: ['Agua', 'Veneno'], moves: ['Poison Sting', 'Water Gun'], spawnTier: 1 },
  'Tentacruel': { hp: 80, atk: 70, def: 65, sp_atk: 80, sp_def: 120, speed: 100, type: ['Agua', 'Veneno'], moves: ['Surf', 'Sludge Bomb'], spawnTier: 2 },
  'Geodude': { hp: 40, atk: 80, def: 100, sp_atk: 30, sp_def: 30, speed: 20, type: ['Roca', 'Tierra'], moves: ['Rock Throw', 'Tackle'], spawnTier: 1 },
  'Graveler': { hp: 55, atk: 95, def: 115, sp_atk: 45, sp_def: 45, speed: 35, type: ['Roca', 'Tierra'], moves: ['Rock Slide', 'Earthquake'], spawnTier: 2 },
  'Golem': { hp: 80, atk: 110, def: 130, sp_atk: 55, sp_def: 65, speed: 45, type: ['Roca', 'Tierra'], moves: ['Rock Slide', 'Earthquake'], spawnTier: 3 },
  'Ponyta': { hp: 50, atk: 85, def: 55, sp_atk: 65, sp_def: 65, speed: 90, type: ['Fuego'], moves: ['Ember', 'Stomp'], spawnTier: 2 },
  'Rapidash': { hp: 65, atk: 100, def: 70, sp_atk: 80, sp_def: 80, speed: 105, type: ['Fuego'], moves: ['Fire Blast', 'Agility'], spawnTier: 3 },
  'Slowpoke': { hp: 90, atk: 65, def: 65, sp_atk: 40, sp_def: 40, speed: 15, type: ['Agua', 'Psíquico'], moves: ['Confusion', 'Water Gun'], spawnTier: 1 },
  'Slowbro': { hp: 95, atk: 75, def: 110, sp_atk: 100, sp_def: 80, speed: 30, type: ['Agua', 'Psíquico'], moves: ['Surf', 'Psychic'], spawnTier: 3 },
  'Magnemite': { hp: 25, atk: 35, def: 70, sp_atk: 95, sp_def: 55, speed: 45, type: ['Eléctrico', 'Acero'], moves: ['Thunder Shock', 'Sonic Boom'], spawnTier: 1 },
  'Magneton': { hp: 50, atk: 60, def: 95, sp_atk: 120, sp_def: 70, speed: 70, type: ['Eléctrico', 'Acero'], moves: ['Thunderbolt', 'Tri Attack'], spawnTier: 2 },
  'Farfetch\'d': { hp: 52, atk: 65, def: 55, sp_atk: 58, sp_def: 62, speed: 60, type: ['Normal', 'Volador'], moves: ['Slash', 'Swords Dance'], spawnTier: 2 }
};

const POKEMON_PART_2 = {
  'Doduo': { hp: 35, atk: 85, def: 45, sp_atk: 35, sp_def: 35, speed: 75, type: ['Normal', 'Volador'], moves: ['Peck', 'Fury Attack'], spawnTier: 1 },
  'Dodrio': { hp: 60, atk: 110, def: 70, sp_atk: 60, sp_def: 60, speed: 100, type: ['Normal', 'Volador'], moves: ['Drill Peck', 'Tri Attack'], spawnTier: 2 },
  'Seel': { hp: 65, atk: 45, def: 55, sp_atk: 45, sp_def: 70, speed: 45, type: ['Agua'], moves: ['Headbutt', 'Icy Wind'], spawnTier: 1 },
  'Dewgong': { hp: 90, atk: 70, def: 80, sp_atk: 70, sp_def: 95, speed: 70, type: ['Agua', 'Hielo'], moves: ['Aurora Beam', 'Surf'], spawnTier: 2 },
  'Grimer': { hp: 80, atk: 80, def: 50, sp_atk: 40, sp_def: 50, speed: 25, type: ['Veneno'], moves: ['Pound', 'Sludge'], spawnTier: 1 },
  'Muk': { hp: 105, atk: 105, def: 75, sp_atk: 65, sp_def: 100, speed: 50, type: ['Veneno'], moves: ['Sludge Bomb', 'Acid Armor'], spawnTier: 3 },
  'Shellder': { hp: 30, atk: 65, def: 100, sp_atk: 45, sp_def: 25, speed: 40, type: ['Agua'], moves: ['Tackle', 'Clamp'], spawnTier: 1 },
  'Cloyster': { hp: 50, atk: 95, def: 180, sp_atk: 85, sp_def: 45, speed: 70, type: ['Agua', 'Hielo'], moves: ['Spike Cannon', 'Ice Beam'], spawnTier: 3 },
  'Gastly': { hp: 30, atk: 35, def: 30, sp_atk: 100, sp_def: 35, speed: 80, type: ['Fantasma', 'Veneno'], moves: ['Lick', 'Hypnosis'], spawnTier: 1 },
  'Haunter': { hp: 45, atk: 50, def: 45, sp_atk: 115, sp_def: 55, speed: 95, type: ['Fantasma', 'Veneno'], moves: ['Lick', 'Shadow Ball'], spawnTier: 2 },
  'Gengar': { hp: 60, atk: 65, def: 60, sp_atk: 130, sp_def: 75, speed: 110, type: ['Fantasma', 'Veneno'], moves: ['Shadow Ball', 'Hypnosis'], spawnTier: 3 },
  'Onix': { hp: 35, atk: 45, def: 160, sp_atk: 30, sp_def: 45, speed: 70, type: ['Roca', 'Tierra'], moves: ['Rock Throw', 'Bind'], spawnTier: 2 },
  'Drowzee': { hp: 60, atk: 48, def: 45, sp_atk: 43, sp_def: 90, speed: 42, type: ['Psíquico'], moves: ['Pound', 'Hypnosis'], spawnTier: 1 },
  'Hypno': { hp: 85, atk: 73, def: 70, sp_atk: 73, sp_def: 115, speed: 67, type: ['Psíquico'], moves: ['Psychic', 'Headbutt'], spawnTier: 2 },
  'Krabby': { hp: 30, atk: 105, def: 90, sp_atk: 25, sp_def: 25, speed: 50, type: ['Agua'], moves: ['Bubble', 'Vice Grip'], spawnTier: 1 },
  'Kingler': { hp: 55, atk: 130, def: 115, sp_atk: 50, sp_def: 50, speed: 75, type: ['Agua'], moves: ['Crabhammer', 'Stomp'], spawnTier: 2 },
  'Voltorb': { hp: 40, atk: 30, def: 50, sp_atk: 55, sp_def: 55, speed: 100, type: ['Eléctrico'], moves: ['Tackle', 'Spark'], spawnTier: 1 },
  'Electrode': { hp: 60, atk: 50, def: 70, sp_atk: 80, sp_def: 80, speed: 140, type: ['Eléctrico'], moves: ['Thunderbolt', 'Explosion'], spawnTier: 2 },
  'Exeggcute': { hp: 60, atk: 40, def: 80, sp_atk: 60, sp_def: 45, speed: 40, type: ['Planta', 'Psíquico'], moves: ['Barrage', 'Hypnosis'], spawnTier: 2 },
  'Exeggutor': { hp: 95, atk: 95, def: 85, sp_atk: 125, sp_def: 65, speed: 55, type: ['Planta', 'Psíquico'], moves: ['Psychic', 'Solar Beam'], spawnTier: 3 },
  'Cubone': { hp: 50, atk: 50, def: 95, sp_atk: 40, sp_def: 50, speed: 35, type: ['Tierra'], moves: ['Bone Club', 'Headbutt'], spawnTier: 1 },
  'Marowak': { hp: 60, atk: 80, def: 110, sp_atk: 50, sp_def: 80, speed: 45, type: ['Tierra'], moves: ['Bonemerang', 'Thrash'], spawnTier: 2 },
  'Hitmonlee': { hp: 50, atk: 120, def: 53, sp_atk: 35, sp_def: 110, speed: 87, type: ['Lucha'], moves: ['High Jump Kick', 'Rolling Kick'], spawnTier: 2 },
  'Hitmonchan': { hp: 50, atk: 105, def: 79, sp_atk: 35, sp_def: 110, speed: 76, type: ['Lucha'], moves: ['Mach Punch', 'Ice Punch'], spawnTier: 2 },
  'Lickitung': { hp: 90, atk: 55, def: 75, sp_atk: 60, sp_def: 75, speed: 30, type: ['Normal'], moves: ['Lick', 'Stomp'], spawnTier: 2 },
  'Koffing': { hp: 40, atk: 65, def: 95, sp_atk: 60, sp_def: 45, speed: 35, type: ['Veneno'], moves: ['Smog', 'Sludge'], spawnTier: 1 },
  'Weezing': { hp: 65, atk: 90, def: 120, sp_atk: 85, sp_def: 70, speed: 60, type: ['Veneno'], moves: ['Sludge Bomb', 'Explosion'], spawnTier: 2 },
  'Rhyhorn': { hp: 80, atk: 85, def: 95, sp_atk: 30, sp_def: 30, speed: 25, type: ['Tierra', 'Roca'], moves: ['Horn Attack', 'Stomp'], spawnTier: 2 },
  'Rhydon': { hp: 105, atk: 130, def: 120, sp_atk: 45, sp_def: 45, speed: 40, type: ['Tierra', 'Roca'], moves: ['Earthquake', 'Rock Slide'], spawnTier: 3 },
  'Chansey': { hp: 250, atk: 5, def: 5, sp_atk: 35, sp_def: 105, speed: 50, type: ['Normal'], moves: ['Soft-Boiled', 'Double-Edge'], spawnTier: 3 },
  'Tangela': { hp: 65, atk: 55, def: 115, sp_atk: 100, sp_def: 40, speed: 60, type: ['Planta'], moves: ['Vine Whip', 'Mega Drain'], spawnTier: 2 },
  'Kangaskhan': { hp: 105, atk: 95, def: 80, sp_atk: 40, sp_def: 80, speed: 90, type: ['Normal'], moves: ['Comet Punch', 'Mega Punch'], spawnTier: 3 },
  'Horsea': { hp: 30, atk: 40, def: 70, sp_atk: 70, sp_def: 25, speed: 60, type: ['Agua'], moves: ['Bubble', 'Water Gun'], spawnTier: 1 },
  'Seadra': { hp: 55, atk: 65, def: 95, sp_atk: 95, sp_def: 45, speed: 85, type: ['Agua'], moves: ['Hydro Pump', 'Twister'], spawnTier: 2 },
  'Goldeen': { hp: 45, atk: 67, def: 60, sp_atk: 35, sp_def: 50, speed: 63, type: ['Agua'], moves: ['Peck', 'Supersonic'], spawnTier: 1 },
  'Seaking': { hp: 80, atk: 92, def: 65, sp_atk: 65, sp_def: 80, speed: 68, type: ['Agua'], moves: ['Waterfall', 'Horn Drill'], spawnTier: 2 },
  'Staryu': { hp: 30, atk: 45, def: 55, sp_atk: 70, sp_def: 55, speed: 85, type: ['Agua'], moves: ['Tackle', 'Water Gun'], spawnTier: 1 },
  'Starmie': { hp: 60, atk: 75, def: 85, sp_atk: 100, sp_def: 85, speed: 115, type: ['Agua', 'Psíquico'], moves: ['Surf', 'Psychic'], spawnTier: 3 },
  'Mr. Mime': { hp: 40, atk: 45, def: 65, sp_atk: 100, sp_def: 120, speed: 90, type: ['Psíquico'], moves: ['Confusion', 'Barrier'], spawnTier: 2 },
  'Scyther': { hp: 70, atk: 110, def: 80, sp_atk: 55, sp_def: 80, speed: 105, type: ['Bicho', 'Volador'], moves: ['Slash', 'Wing Attack'], spawnTier: 2 },
  'Jynx': { hp: 65, atk: 50, def: 35, sp_atk: 115, sp_def: 95, speed: 95, type: ['Hielo', 'Psíquico'], moves: ['Ice Punch', 'Lovely Kiss'], spawnTier: 2 },
  'Electabuzz': { hp: 65, atk: 83, def: 57, sp_atk: 95, sp_def: 85, speed: 105, type: ['Eléctrico'], moves: ['Thunder Punch', 'Thunderbolt'], spawnTier: 2 },
  'Magmar': { hp: 65, atk: 95, def: 57, sp_atk: 100, sp_def: 85, speed: 93, type: ['Fuego'], moves: ['Fire Punch', 'Flamethrower'], spawnTier: 2 },
  'Pinsir': { hp: 65, atk: 125, def: 100, sp_atk: 55, sp_def: 70, speed: 85, type: ['Bicho'], moves: ['Vice Grip', 'Submission'], spawnTier: 2 },
  'Tauros': { hp: 75, atk: 100, def: 95, sp_atk: 40, sp_def: 70, speed: 110, type: ['Normal'], moves: ['Tackle', 'Take Down'], spawnTier: 2 },
  'Magikarp': { hp: 20, atk: 10, def: 55, sp_atk: 15, sp_def: 20, speed: 80, type: ['Agua'], moves: ['Splash', 'Tackle'], spawnTier: 1 },
  'Gyarados': { hp: 95, atk: 125, def: 79, sp_atk: 60, sp_def: 100, speed: 81, type: ['Agua', 'Volador'], moves: ['Hydro Pump', 'Dragon Rage'], spawnTier: 4 },
  'Lapras': { hp: 130, atk: 85, def: 80, sp_atk: 85, sp_def: 95, speed: 60, type: ['Agua', 'Hielo'], moves: ['Surf', 'Ice Beam'], spawnTier: 4 },
  'Ditto': { hp: 48, atk: 48, def: 48, sp_atk: 48, sp_def: 48, speed: 48, type: ['Normal'], moves: ['Transform'], spawnTier: 2 },
  'Eevee': { hp: 55, atk: 55, def: 50, sp_atk: 45, sp_def: 65, speed: 55, type: ['Normal'], moves: ['Tackle', 'Quick Attack'], spawnTier: 1 },
  'Vaporeon': { hp: 130, atk: 65, def: 60, sp_atk: 110, sp_def: 95, speed: 65, type: ['Agua'], moves: ['Surf', 'Acid Armor'], spawnTier: 3 },
  'Jolteon': { hp: 65, atk: 65, def: 60, sp_atk: 110, sp_def: 95, speed: 130, type: ['Eléctrico'], moves: ['Thunderbolt', 'Pin Missile'], spawnTier: 3 },
  'Flareon': { hp: 65, atk: 130, def: 60, sp_atk: 95, sp_def: 110, speed: 65, type: ['Fuego'], moves: ['Flamethrower', 'Fire Blast'], spawnTier: 3 },
  'Porygon': { hp: 65, atk: 60, def: 70, sp_atk: 85, sp_def: 75, speed: 40, type: ['Normal'], moves: ['Tri Attack', 'Conversion'], spawnTier: 2 },
  'Omanyte': { hp: 35, atk: 40, def: 100, sp_atk: 90, sp_def: 55, speed: 35, type: ['Roca', 'Agua'], moves: ['Water Gun', 'Withdraw'], spawnTier: 2 },
  'Omastar': { hp: 70, atk: 60, def: 125, sp_atk: 115, sp_def: 70, speed: 55, type: ['Roca', 'Agua'], moves: ['Spike Cannon', 'Hydro Pump'], spawnTier: 3 },
  'Kabuto': { hp: 30, atk: 80, def: 90, sp_atk: 55, sp_def: 45, speed: 55, type: ['Roca', 'Agua'], moves: ['Scratch', 'Harden'], spawnTier: 2 },
  'Kabutops': { hp: 60, atk: 115, def: 105, sp_atk: 65, sp_def: 70, speed: 80, type: ['Roca', 'Agua'], moves: ['Slash', 'Mega Drain'], spawnTier: 3 },
  'Aerodactyl': { hp: 80, atk: 105, def: 65, sp_atk: 60, sp_def: 75, speed: 130, type: ['Roca', 'Volador'], moves: ['Wing Attack', 'Ancient Power'], spawnTier: 4 },
  'Snorlax': { hp: 160, atk: 110, def: 65, sp_atk: 65, sp_def: 110, speed: 30, type: ['Normal'], moves: ['Body Slam', 'Rest'], spawnTier: 4 },
  'Articuno': { hp: 90, atk: 85, def: 100, sp_atk: 95, sp_def: 125, speed: 85, type: ['Hielo', 'Volador'], moves: ['Ice Beam', 'Blizzard'], spawnTier: 5 },
  'Zapdos': { hp: 90, atk: 90, def: 85, sp_atk: 125, sp_def: 90, speed: 100, type: ['Eléctrico', 'Volador'], moves: ['Drill Peck', 'Thunderbolt'], spawnTier: 5 },
  'Moltres': { hp: 90, atk: 100, def: 90, sp_atk: 125, sp_def: 85, speed: 90, type: ['Fuego', 'Volador'], moves: ['Fire Blast', 'Sky Attack'], spawnTier: 5 },
  'Dratini': { hp: 41, atk: 64, def: 45, sp_atk: 50, sp_def: 50, speed: 50, type: ['Dragón'], moves: ['Wrap', 'Thunder Wave'], spawnTier: 2 },
  'Dragonair': { hp: 61, atk: 84, def: 65, sp_atk: 70, sp_def: 70, speed: 70, type: ['Dragón'], moves: ['Slam', 'Dragon Rage'], spawnTier: 3 },
  'Dragonite': { hp: 91, atk: 134, def: 95, sp_atk: 100, sp_def: 100, speed: 80, type: ['Dragón', 'Volador'], moves: ['Outrage', 'Wing Attack'], spawnTier: 4 },
  'Mewtwo': { hp: 106, atk: 110, def: 90, sp_atk: 154, sp_def: 90, speed: 130, type: ['Psíquico'], moves: ['Psychic', 'Recover'], spawnTier: 5 },
  'Mew': { hp: 100, atk: 100, def: 100, sp_atk: 100, sp_def: 100, speed: 100, type: ['Psíquico'], moves: ['Psychic', 'Metronome'], spawnTier: 5 },
  'Chikorita': { hp: 45, atk: 49, def: 65, sp_atk: 49, sp_def: 65, speed: 45, type: ['Planta'], moves: ['Tackle', 'Razor Leaf'], spawnTier: 1 },
  'Bayleef': { hp: 60, atk: 62, def: 80, sp_atk: 63, sp_def: 80, speed: 60, type: ['Planta'], moves: ['Razor Leaf', 'Reflect'], spawnTier: 2 },
  'Meganium': { hp: 80, atk: 82, def: 100, sp_atk: 83, sp_def: 100, speed: 80, type: ['Planta'], moves: ['Solar Beam', 'Synthesis'], spawnTier: 3 },
  'Cyndaquil': { hp: 39, atk: 52, def: 43, sp_atk: 60, sp_def: 50, speed: 65, type: ['Fuego'], moves: ['Tackle', 'Ember'], spawnTier: 1 },
  'Quilava': { hp: 58, atk: 64, def: 58, sp_atk: 80, sp_def: 65, speed: 80, type: ['Fuego'], moves: ['Flame Wheel', 'Quick Attack'], spawnTier: 2 },
  'Typhlosion': { hp: 78, atk: 84, def: 78, sp_atk: 109, sp_def: 85, speed: 100, type: ['Fuego'], moves: ['Flamethrower', 'Thunder Punch'], spawnTier: 3 },
  'Totodile': { hp: 50, atk: 65, def: 64, sp_atk: 44, sp_def: 48, speed: 43, type: ['Agua'], moves: ['Scratch', 'Water Gun'], spawnTier: 1 },
  'Croconaw': { hp: 65, atk: 80, def: 80, sp_atk: 59, sp_def: 63, speed: 58, type: ['Agua'], moves: ['Bite', 'Water Gun'], spawnTier: 2 },
  'Feraligatr': { hp: 85, atk: 105, def: 100, sp_atk: 79, sp_def: 83, speed: 78, type: ['Agua'], moves: ['Hydro Pump', 'Slash'], spawnTier: 3 },
  'Sentret': { hp: 35, atk: 46, def: 34, sp_atk: 35, sp_def: 45, speed: 20, type: ['Normal'], moves: ['Tackle', 'Quick Attack'], spawnTier: 1 },
  'Furret': { hp: 85, atk: 76, def: 64, sp_atk: 45, sp_def: 55, speed: 90, type: ['Normal'], moves: ['Quick Attack', 'Slam'], spawnTier: 2 },
  'Hoothoot': { hp: 60, atk: 30, def: 30, sp_atk: 36, sp_def: 56, speed: 50, type: ['Normal', 'Volador'], moves: ['Peck', 'Hypnosis'], spawnTier: 1 },
  'Noctowl': { hp: 100, atk: 50, def: 50, sp_atk: 86, sp_def: 96, speed: 70, type: ['Normal', 'Volador'], moves: ['Take Down', 'Dream Eater'], spawnTier: 2 },
  'Ledyba': { hp: 40, atk: 20, def: 30, sp_atk: 40, sp_def: 80, speed: 55, type: ['Bicho', 'Volador'], moves: ['Tackle', 'Comet Punch'], spawnTier: 1 },
  'Ledian': { hp: 55, atk: 35, def: 50, sp_atk: 55, sp_def: 110, speed: 85, type: ['Bicho', 'Volador'], moves: ['Comet Punch', 'Reflect'], spawnTier: 2 },
  'Spinarak': { hp: 40, atk: 60, def: 40, sp_atk: 40, sp_def: 40, speed: 30, type: ['Bicho', 'Veneno'], moves: ['Poison Sting', 'Constrict'], spawnTier: 1 },
  'Ariados': { hp: 70, atk: 90, def: 70, sp_atk: 60, sp_def: 70, speed: 40, type: ['Bicho', 'Veneno'], moves: ['Sludge Bomb', 'Psychic'], spawnTier: 2 }
};

const POKEMON_PART_3 = {
  'Crobat': { hp: 85, atk: 90, def: 80, sp_atk: 70, sp_def: 80, speed: 130, type: ['Veneno', 'Volador'], moves: ['Wing Attack', 'Confuse Ray'], spawnTier: 3 },
  'Chinchou': { hp: 75, atk: 38, def: 38, sp_atk: 56, sp_def: 56, speed: 67, type: ['Agua', 'Eléctrico'], moves: ['Bubble', 'Thunder Wave'], spawnTier: 1 },
  'Lanturn': { hp: 125, atk: 58, def: 58, sp_atk: 76, sp_def: 76, speed: 67, type: ['Agua', 'Eléctrico'], moves: ['Surf', 'Thunderbolt'], spawnTier: 2 },
  'Pichu': { hp: 20, atk: 40, def: 15, sp_atk: 35, sp_def: 35, speed: 60, type: ['Eléctrico'], moves: ['Thunder Shock', 'Charm'], spawnTier: 1 },
  'Cleffa': { hp: 50, atk: 25, def: 28, sp_atk: 45, sp_def: 55, speed: 15, type: ['Normal'], moves: ['Pound', 'Charm'], spawnTier: 1 },
  'Igglybuff': { hp: 90, atk: 30, def: 15, sp_atk: 40, sp_def: 20, speed: 15, type: ['Normal'], moves: ['Sing', 'Charm'], spawnTier: 1 },
  'Togepi': { hp: 35, atk: 20, def: 65, sp_atk: 40, sp_def: 65, speed: 20, type: ['Normal'], moves: ['Metronome', 'Charm'], spawnTier: 1 },
  'Togetic': { hp: 55, atk: 40, def: 85, sp_atk: 80, sp_def: 105, speed: 40, type: ['Normal', 'Volador'], moves: ['Double-Edge', 'Metronome'], spawnTier: 2 },
  'Natu': { hp: 40, atk: 50, def: 45, sp_atk: 70, sp_def: 45, speed: 70, type: ['Psíquico', 'Volador'], moves: ['Peck', 'Night Shade'], spawnTier: 1 },
  'Xatu': { hp: 65, atk: 75, def: 70, sp_atk: 95, sp_def: 70, speed: 95, type: ['Psíquico', 'Volador'], moves: ['Psychic', 'Fly'], spawnTier: 2 },
  'Mareep': { hp: 55, atk: 40, def: 40, sp_atk: 65, sp_def: 45, speed: 35, type: ['Eléctrico'], moves: ['Tackle', 'Thunder Shock'], spawnTier: 1 },
  'Flaaffy': { hp: 70, atk: 55, def: 55, sp_atk: 80, sp_def: 60, speed: 45, type: ['Eléctrico'], moves: ['Thunder Shock', 'Thunder Wave'], spawnTier: 2 },
  'Ampharos': { hp: 90, atk: 75, def: 75, sp_atk: 115, sp_def: 90, speed: 55, type: ['Eléctrico'], moves: ['Thunder Punch', 'Thunder'], spawnTier: 3 },
  'Bellossom': { hp: 75, atk: 80, def: 85, sp_atk: 90, sp_def: 100, speed: 50, type: ['Planta'], moves: ['Petal Dance', 'Solar Beam'], spawnTier: 3 },
  'Marill': { hp: 70, atk: 20, def: 50, sp_atk: 20, sp_def: 50, speed: 40, type: ['Agua'], moves: ['Tackle', 'Water Gun'], spawnTier: 1 },
  'Azumarill': { hp: 100, atk: 50, def: 80, sp_atk: 50, sp_def: 80, speed: 50, type: ['Agua'], moves: ['Bubble Beam', 'Rollout'], spawnTier: 2 },
  'Sudowoodo': { hp: 70, atk: 100, def: 115, sp_atk: 30, sp_def: 65, speed: 30, type: ['Roca'], moves: ['Rock Slide', 'Low Kick'], spawnTier: 2 },
  'Politoed': { hp: 90, atk: 75, def: 75, sp_atk: 90, sp_def: 100, speed: 70, type: ['Agua'], moves: ['Surf', 'Perish Song'], spawnTier: 3 },
  'Hoppip': { hp: 35, atk: 35, def: 40, sp_atk: 35, sp_def: 55, speed: 50, type: ['Planta', 'Volador'], moves: ['Splash', 'Synthesis'], spawnTier: 1 },
  'Skiploom': { hp: 55, atk: 45, def: 50, sp_atk: 45, sp_def: 65, speed: 80, type: ['Planta', 'Volador'], moves: ['Tackle', 'Leech Seed'], spawnTier: 2 },
  'Jumpluff': { hp: 75, atk: 55, def: 70, sp_atk: 55, sp_def: 85, speed: 110, type: ['Planta', 'Volador'], moves: ['Cotton Spore', 'Mega Drain'], spawnTier: 3 },
  'Aipom': { hp: 55, atk: 70, def: 55, sp_atk: 40, sp_def: 55, speed: 85, type: ['Normal'], moves: ['Scratch', 'Baton Pass'], spawnTier: 2 },
  'Sunkern': { hp: 30, atk: 30, def: 30, sp_atk: 30, sp_def: 30, speed: 30, type: ['Planta'], moves: ['Absorb', 'Growth'], spawnTier: 1 },
  'Sunflora': { hp: 75, atk: 75, def: 55, sp_atk: 105, sp_def: 85, speed: 30, type: ['Planta'], moves: ['Petal Dance', 'Solar Beam'], spawnTier: 2 },
  'Yanma': { hp: 65, atk: 65, def: 45, sp_atk: 75, sp_def: 45, speed: 95, type: ['Bicho', 'Volador'], moves: ['Tackle', 'Sonic Boom'], spawnTier: 2 },
  'Wooper': { hp: 55, atk: 45, def: 45, sp_atk: 25, sp_def: 25, speed: 15, type: ['Agua', 'Tierra'], moves: ['Water Gun', 'Mud-Slap'], spawnTier: 1 },
  'Quagsire': { hp: 95, atk: 85, def: 85, sp_atk: 65, sp_def: 65, speed: 35, type: ['Agua', 'Tierra'], moves: ['Earthquake', 'Surf'], spawnTier: 2 },
  'Espeon': { hp: 65, atk: 65, def: 60, sp_atk: 130, sp_def: 95, speed: 110, type: ['Psíquico'], moves: ['Psychic', 'Morning Sun'], spawnTier: 4 },
  'Umbreon': { hp: 95, atk: 65, def: 110, sp_atk: 60, sp_def: 130, speed: 65, type: ['Siniestro'], moves: ['Faint Attack', 'Confuse Ray'], spawnTier: 4 },
  'Murkrow': { hp: 60, atk: 85, def: 42, sp_atk: 85, sp_def: 42, speed: 91, type: ['Siniestro', 'Volador'], moves: ['Peck', 'Faint Attack'], spawnTier: 2 },
  'Slowking': { hp: 95, atk: 75, def: 80, sp_atk: 100, sp_def: 110, speed: 30, type: ['Agua', 'Psíquico'], moves: ['Psychic', 'Surf'], spawnTier: 3 },
  'Misdreavus': { hp: 60, atk: 60, def: 60, sp_atk: 85, sp_def: 85, speed: 85, type: ['Fantasma'], moves: ['Psybeam', 'Pain Split'], spawnTier: 2 },
  'Unown': { hp: 48, atk: 72, def: 48, sp_atk: 72, sp_def: 48, speed: 48, type: ['Psíquico'], moves: ['Hidden Power'], spawnTier: 1 },
  'Wobbuffet': { hp: 190, atk: 33, def: 58, sp_atk: 33, sp_def: 58, speed: 33, type: ['Psíquico'], moves: ['Counter', 'Mirror Coat'], spawnTier: 3 },
  'Girafarig': { hp: 70, atk: 80, def: 65, sp_atk: 90, sp_def: 65, speed: 85, type: ['Normal', 'Psíquico'], moves: ['Stomp', 'Psybeam'], spawnTier: 2 },
  'Pineco': { hp: 50, atk: 65, def: 90, sp_atk: 35, sp_def: 35, speed: 15, type: ['Bicho'], moves: ['Tackle', 'Self-Destruct'], spawnTier: 1 },
  'Forretress': { hp: 75, atk: 90, def: 140, sp_atk: 60, sp_def: 60, speed: 40, type: ['Bicho', 'Acero'], moves: ['Explosion', 'Spikes'], spawnTier: 3 },
  'Dunsparce': { hp: 100, atk: 70, def: 70, sp_atk: 65, sp_def: 65, speed: 45, type: ['Normal'], moves: ['Glare', 'Headbutt'], spawnTier: 2 },
  'Gligar': { hp: 65, atk: 75, def: 105, sp_atk: 35, sp_def: 65, speed: 85, type: ['Tierra', 'Volador'], moves: ['Poison Sting', 'Faint Attack'], spawnTier: 2 },
  'Steelix': { hp: 75, atk: 85, def: 200, sp_atk: 55, sp_def: 65, speed: 30, type: ['Acero', 'Tierra'], moves: ['Iron Tail', 'Earthquake'], spawnTier: 4 },
  'Snubbull': { hp: 60, atk: 80, def: 50, sp_atk: 40, sp_def: 40, speed: 30, type: ['Normal'], moves: ['Tackle', 'Bite'], spawnTier: 1 },
  'Granbull': { hp: 90, atk: 120, def: 75, sp_atk: 60, sp_def: 60, speed: 45, type: ['Normal'], moves: ['Bite', 'Take Down'], spawnTier: 2 },
  'Qwilfish': { hp: 65, atk: 95, def: 75, sp_atk: 55, sp_def: 55, speed: 85, type: ['Agua', 'Veneno'], moves: ['Pin Missile', 'Sludge Bomb'], spawnTier: 2 },
  'Scizor': { hp: 70, atk: 130, def: 100, sp_atk: 55, sp_def: 80, speed: 65, type: ['Bicho', 'Acero'], moves: ['Metal Claw', 'Slash'], spawnTier: 4 },
  'Shuckle': { hp: 20, atk: 10, def: 230, sp_atk: 10, sp_def: 230, speed: 5, type: ['Bicho', 'Roca'], moves: ['Wrap', 'Toxic'], spawnTier: 2 },
  'Heracross': { hp: 80, atk: 125, def: 75, sp_atk: 40, sp_def: 95, speed: 85, type: ['Bicho', 'Lucha'], moves: ['Megahorn', 'Reversal'], spawnTier: 3 },
  'Sneasel': { hp: 55, atk: 95, def: 55, sp_atk: 35, sp_def: 75, speed: 115, type: ['Siniestro', 'Hielo'], moves: ['Faint Attack', 'Icy Wind'], spawnTier: 2 },
  'Teddiursa': { hp: 60, atk: 80, def: 50, sp_atk: 50, sp_def: 50, speed: 40, type: ['Normal'], moves: ['Scratch', 'Lick'], spawnTier: 1 },
  'Ursaring': { hp: 90, atk: 130, def: 75, sp_atk: 75, sp_def: 75, speed: 55, type: ['Normal'], moves: ['Slash', 'Faint Attack'], spawnTier: 3 },
  'Slugma': { hp: 40, atk: 40, def: 40, sp_atk: 70, sp_def: 40, speed: 20, type: ['Fuego'], moves: ['Smog', 'Ember'], spawnTier: 1 },
  'Magcargo': { hp: 50, atk: 50, def: 120, sp_atk: 80, sp_def: 80, speed: 30, type: ['Fuego', 'Roca'], moves: ['Flamethrower', 'Rock Slide'], spawnTier: 2 },
  'Swinub': { hp: 50, atk: 50, def: 40, sp_atk: 30, sp_def: 30, speed: 50, type: ['Hielo', 'Tierra'], moves: ['Tackle', 'Powder Snow'], spawnTier: 1 },
  'Piloswine': { hp: 100, atk: 100, def: 80, sp_atk: 60, sp_def: 60, speed: 50, type: ['Hielo', 'Tierra'], moves: ['Blizzard', 'Earthquake'], spawnTier: 2 },
  'Corsola': { hp: 55, atk: 55, def: 85, sp_atk: 65, sp_def: 85, speed: 35, type: ['Agua', 'Roca'], moves: ['Bubble Beam', 'Recover'], spawnTier: 2 },
  'Remoraid': { hp: 35, atk: 65, def: 35, sp_atk: 65, sp_def: 35, speed: 65, type: ['Agua'], moves: ['Water Gun', 'Aurora Beam'], spawnTier: 1 },
  'Octillery': { hp: 75, atk: 105, def: 75, sp_atk: 105, sp_def: 75, speed: 45, type: ['Agua'], moves: ['Octazooka', 'Ice Beam'], spawnTier: 2 },
  'Delibird': { hp: 45, atk: 55, def: 45, sp_atk: 65, sp_def: 45, speed: 75, type: ['Hielo', 'Volador'], moves: ['Present'], spawnTier: 2 },
  'Mantine': { hp: 65, atk: 40, def: 70, sp_atk: 80, sp_def: 140, speed: 70, type: ['Agua', 'Volador'], moves: ['Bubble Beam', 'Wing Attack'], spawnTier: 3 },
  'Skarmory': { hp: 65, atk: 80, def: 140, sp_atk: 40, sp_def: 70, speed: 70, type: ['Acero', 'Volador'], moves: ['Peck', 'Steel Wing'], spawnTier: 3 },
  'Houndour': { hp: 45, atk: 60, def: 30, sp_atk: 80, sp_def: 50, speed: 65, type: ['Siniestro', 'Fuego'], moves: ['Ember', 'Bite'], spawnTier: 2 },
  'Houndoom': { hp: 75, atk: 90, def: 50, sp_atk: 110, sp_def: 80, speed: 95, type: ['Siniestro', 'Fuego'], moves: ['Crunch', 'Flamethrower'], spawnTier: 3 },
  'Kingdra': { hp: 75, atk: 95, def: 95, sp_atk: 95, sp_def: 95, speed: 85, type: ['Agua', 'Dragón'], moves: ['Hydro Pump', 'Dragon Breath'], spawnTier: 4 },
  'Phanpy': { hp: 90, atk: 60, def: 60, sp_atk: 40, sp_def: 40, speed: 40, type: ['Tierra'], moves: ['Tackle', 'Rollout'], spawnTier: 1 },
  'Donphan': { hp: 90, atk: 120, def: 120, sp_atk: 60, sp_def: 60, speed: 50, type: ['Tierra'], moves: ['Earthquake', 'Rollout'], spawnTier: 3 },
  'Porygon2': { hp: 85, atk: 80, def: 90, sp_atk: 105, sp_def: 95, speed: 60, type: ['Normal'], moves: ['Tri Attack', 'Conversion 2'], spawnTier: 4 },
  'Stantler': { hp: 73, atk: 95, def: 62, sp_atk: 85, sp_def: 65, speed: 85, type: ['Normal'], moves: ['Stomp', 'Hypnosis'], spawnTier: 2 },
  'Smeargle': { hp: 55, atk: 20, def: 35, sp_atk: 20, sp_def: 45, speed: 75, type: ['Normal'], moves: ['Sketch'], spawnTier: 2 },
  'Tyrogue': { hp: 35, atk: 35, def: 35, sp_atk: 35, sp_def: 35, speed: 35, type: ['Lucha'], moves: ['Tackle'], spawnTier: 1 },
  'Hitmontop': { hp: 50, atk: 95, def: 95, sp_atk: 35, sp_def: 110, speed: 70, type: ['Lucha'], moves: ['Rolling Kick', 'Rapid Spin'], spawnTier: 2 },
  'Smoochum': { hp: 45, atk: 30, def: 15, sp_atk: 85, sp_def: 65, speed: 65, type: ['Hielo', 'Psíquico'], moves: ['Pound', 'Sweet Kiss'], spawnTier: 1 },
  'Elekid': { hp: 45, atk: 63, def: 37, sp_atk: 65, sp_def: 55, speed: 95, type: ['Eléctrico'], moves: ['Thunder Punch', 'Quick Attack'], spawnTier: 1 },
  'Magby': { hp: 45, atk: 75, def: 37, sp_atk: 70, sp_def: 55, speed: 83, type: ['Fuego'], moves: ['Ember', 'Smog'], spawnTier: 1 },
  'Miltank': { hp: 95, atk: 80, def: 105, sp_atk: 40, sp_def: 70, speed: 100, type: ['Normal'], moves: ['Stomp', 'Milk Drink'], spawnTier: 3 },
  'Blissey': { hp: 255, atk: 10, def: 10, sp_atk: 75, sp_def: 135, speed: 55, type: ['Normal'], moves: ['Soft-Boiled', 'Double-Edge'], spawnTier: 4 },
  'Raikou': { hp: 90, atk: 85, def: 75, sp_atk: 115, sp_def: 100, speed: 115, type: ['Eléctrico'], moves: ['Thunder', 'Spark'], spawnTier: 5 },
  'Entei': { hp: 115, atk: 115, def: 85, sp_atk: 90, sp_def: 75, speed: 100, type: ['Fuego'], moves: ['Fire Blast', 'Stomp'], spawnTier: 5 },
  'Suicune': { hp: 100, atk: 75, def: 115, sp_atk: 90, sp_def: 115, speed: 85, type: ['Agua'], moves: ['Hydro Pump', 'Bubble Beam'], spawnTier: 5 },
  'Larvitar': { hp: 50, atk: 64, def: 50, sp_atk: 45, sp_def: 50, speed: 41, type: ['Roca', 'Tierra'], moves: ['Bite', 'Rock Slide'], spawnTier: 2 },
  'Pupitar': { hp: 70, atk: 84, def: 70, sp_atk: 65, sp_def: 70, speed: 51, type: ['Roca', 'Tierra'], moves: ['Rock Slide', 'Dark Pulse'], spawnTier: 3 },
  'Tyranitar': { hp: 100, atk: 134, def: 110, sp_atk: 95, sp_def: 100, speed: 61, type: ['Roca', 'Siniestro'], moves: ['Crunch', 'Earthquake'], spawnTier: 4 },
  'Lugia': { hp: 106, atk: 90, def: 130, sp_atk: 90, sp_def: 154, speed: 110, type: ['Psíquico', 'Volador'], moves: ['Aeroblast', 'Psychic'], spawnTier: 5 },
  'Ho-Oh': { hp: 106, atk: 130, def: 90, sp_atk: 110, sp_def: 154, speed: 90, type: ['Fuego', 'Volador'], moves: ['Sacred Fire', 'Brave Bird'], spawnTier: 5 },
  'Celebi': { hp: 100, atk: 100, def: 100, sp_atk: 100, sp_def: 100, speed: 100, type: ['Psíquico', 'Planta'], moves: ['Solar Beam', 'Psychic'], spawnTier: 5 }
};

const POKEMON_SPECIES  = { ...POKEMON_PART_1, ...POKEMON_PART_2, ...POKEMON_PART_3 };
